id: P80333936
initial_creation_type: ocr
source_metadata:
  volumes:
    a73995e04bd94fb5b3eb66621c4ff96a:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: མདོ་སྡེ་དགོངས་པ་ངེས་པར་འགྲེལ་པའི་མདོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1880
      volume_number: 116
